version: 2

jobs:
  test:
    docker:
      - image: circleci/node:11.10.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM Packages
          command: |
            npm install
      - run:
          name: Unit Tests
          command: |
            npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  test_databox:
    jobs:
      - test
