/**
 * Static OpenAPI document of Push API resource
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class State.
* @enum {}
* @readonly
*/
export default class State {
    
        /**
         * value: "DOWN"
         * @const
         */
        "DOWN" = "DOWN";

    
        /**
         * value: "UP"
         * @const
         */
        "UP" = "UP";

    

    /**
    * Returns a <code>State</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:databox/model/State} The enum <code>State</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

