/* tslint:disable */
/* eslint-disable */
/**
 * Static OpenAPI document of Push API resource
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 0.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PushDataAttribute
 */
export interface PushDataAttribute {
    /**
     * 
     * @type {string}
     * @memberof PushDataAttribute
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof PushDataAttribute
     */
    value?: string;
}

/**
 * Check if a given object implements the PushDataAttribute interface.
 */
export function instanceOfPushDataAttribute(value: object): value is PushDataAttribute {
    return true;
}

export function PushDataAttributeFromJSON(json: any): PushDataAttribute {
    return PushDataAttributeFromJSONTyped(json, false);
}

export function PushDataAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PushDataAttribute {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function PushDataAttributeToJSON(value?: PushDataAttribute | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

