/* tslint:disable */
/* eslint-disable */
/**
 * Static OpenAPI document of Push API resource
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 0.4.4-alpha.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const State = {
    Down: 'DOWN',
    Up: 'UP'
} as const;
export type State = typeof State[keyof typeof State];


export function instanceOfState(value: any): boolean {
    for (const key in State) {
        if (Object.prototype.hasOwnProperty.call(State, key)) {
            if (State[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StateFromJSON(json: any): State {
    return StateFromJSONTyped(json, false);
}

export function StateFromJSONTyped(json: any, ignoreDiscriminator: boolean): State {
    return json as State;
}

export function StateToJSON(value?: State | null): any {
    return value as any;
}

