/**
 * Static OpenAPI document of Push API resource
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/databox/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/databox/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Databox);
  }
}(this, function(expect, Databox) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Databox.PushData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PushData', function() {
    it('should create an instance of PushData', function() {
      // uncomment below and update the code to test PushData
      //var instance = new Databox.PushData();
      //expect(instance).to.be.a(Databox.PushData);
    });

    it('should have the property attributes (base name: "attributes")', function() {
      // uncomment below and update the code to test the property attributes
      //var instance = new Databox.PushData();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new Databox.PushData();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new Databox.PushData();
      //expect(instance).to.be();
    });

    it('should have the property periodFrom (base name: "periodFrom")', function() {
      // uncomment below and update the code to test the property periodFrom
      //var instance = new Databox.PushData();
      //expect(instance).to.be();
    });

    it('should have the property periodTo (base name: "periodTo")', function() {
      // uncomment below and update the code to test the property periodTo
      //var instance = new Databox.PushData();
      //expect(instance).to.be();
    });

    it('should have the property unit (base name: "unit")', function() {
      // uncomment below and update the code to test the property unit
      //var instance = new Databox.PushData();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new Databox.PushData();
      //expect(instance).to.be();
    });

  });

}));
