/**
 * Static OpenAPI document of Push API resource
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 0.3.15-sdk.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/databox/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/databox/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Databox);
  }
}(this, function(expect, Databox) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Databox.PushDataAttribute();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PushDataAttribute', function() {
    it('should create an instance of PushDataAttribute', function() {
      // uncomment below and update the code to test PushDataAttribute
      //var instance = new Databox.PushDataAttribute();
      //expect(instance).to.be.a(Databox.PushDataAttribute);
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new Databox.PushDataAttribute();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new Databox.PushDataAttribute();
      //expect(instance).to.be();
    });

  });

}));
