// tslint:disable
/**
 * Static OpenAPI document of Push API resource
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApiResponse
 */
export interface ApiResponse {
    /**
     * @type {string}
     * @memberof ApiResponse
     */
    status?: string;
    /**
     * @type {string}
     * @memberof ApiResponse
     */
    message?: string;
}
