// tslint:disable
/**
 * Static OpenAPI document of Push API resource
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PushDataAttribute
 */
export interface PushDataAttribute {
    /**
     * @type {string}
     * @memberof PushDataAttribute
     */
    key?: string;
    /**
     * @type {string}
     * @memberof PushDataAttribute
     */
    value?: string;
}
